### ISSUE TITLE
不错，加上测试使用就更棒了

### ISSUE THREAD

**Issue by leopku** [Ksloveyuan/gorm-ex#1]

**Comment by Ksloveyuan** [comment]
谢谢支持哈，带例子的使用方法可以参照我写的两篇文章哈。
[Gorm的使用心得和一些常用扩展(一)](https://juejin.im/post/5d29988e6fb9a07efc49b612)
[Gorm的使用心得和一些常用扩展(二)](https://juejin.im/post/5d3093625188251b2569f10e)
